const destinations = [
  {
    from: "England",
    to: "Australia",
    price: "$1000",
    description: "Explore the beautiful landscapes of Australia.",
    time: "10 hours",
    fly_date: "2023-08-01",
  },
  {
    from: "England",
    to: "Asgard",
    price: "$1500",
    description: "Embark on a mythical journey to Asgard.",
    time: "12 hours",
    fly_date: "2023-09-15",
  },
  {
    from: "England",
    to: "Brazil",
    price: "$800",
    description: "Experience the vibrant culture of Brazil.",
    time: "14 hours",
    fly_date: "2023-10-05",
  },
  {
    from: "England",
    to: "Burma",
    price: "$600",
    description: "Discover the hidden gems of Burma.",
    time: "8 hours",
    fly_date: "2023-11-20",
  },
  {
    from: "England",
    to: "Burundi",
    price: "$700",
    description: "Immerse yourself in the beauty of Burundi.",
    time: "10 hours",
    fly_date: "2023-12-10",
  },
  {
    from: "England",
    to: "China",
    price: "$900",
    description: "Experience the rich history and culture of China.",
    time: "12 hours",
    fly_date: "2024-01-15",
  },
  {
    from: "England",
    to: "Congo",
    price: "$750",
    description: "Discover the wonders of Congo's wildlife.",
    time: "11 hours",
    fly_date: "2024-02-05",
  },
  {
    from: "England",
    to: "Dominican Republic",
    price: "$1200",
    description: "Relax on the pristine beaches of the Dominican Republic.",
    time: "9 hours",
    fly_date: "2024-03-20",
  },
  {
    from: "England",
    to: "El Salvador",
    price: "$850",
    description: "Enjoy the tropical beauty of El Salvador.",
    time: "10 hours",
    fly_date: "2024-04-10",
  },
  {
    from: "India",
    to: "England",
    price: "$800",
    description: "Experience the charm of England.",
    time: "11 hours",
    fly_date: "2024-05-15",
  },
  {
    from: "England",
    to: "Iraq",
    price: "$950",
    description: "Discover the historical sites of Iraq.",
    time: "12 hours",
    fly_date: "2024-06-05",
  },
  {
    from: "Italy",
    to: "England",
    price: "$700",
    description: "Indulge in the art and culture of Italy.",
    time: "9 hours",
    fly_date: "2024-07-20",
  },
  {
    from: "England",
    to: "Japan",
    price: "$1300",
    description:
      "Experience the unique blend of tradition and modernity in Japan.",
    time: "11 hours",
    fly_date: "2024-08-10",
  },
  {
    from: "England",
    to: "Russia",
    price: "$1000",
    description: "Explore the vast landscapes of Russia.",
    time: "10 hours",
    fly_date: "2024-09-15",
  },
  {
    from: "England",
    to: "Somalia",
    price: "$600",
    description: "Discover the stunning beaches of Somalia.",
    time: "9 hours",
    fly_date: "2024-10-05",
  },
  {
    from: "England",
    to: "Syria",
    price: "$850",
    description: "Explore the historical treasures of Syria.",
    time: "12 hours",
    fly_date: "2024-11-20",
  },
  {
    from: "United States",
    to: "England",
    price: "$1200",
    description: "Experience the vibrant cities of the United States.",
    time: "10 hours",
    fly_date: "2024-12-10",
  },
  {
    from: "England",
    to: "Yemen",
    price: "$900",
    description: "Discover the rich cultural heritage of Yemen.",
    time: "11 hours",
    fly_date: "2025-01-15",
  },
  {
    from: "Wakanda",
    to: "England",
    price: "$1500",
    description: "Visit the mythical land of Wakanda.",
    time: "12 hours",
    fly_date: "2025-02-05",
  },
];


export default destinations